"""Bundle notices for modules actually linked into both Linux server targets."""
import argparse
import json
import os
from pathlib import Path
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = Path(__file__).resolve().parent.parent
server = root / 'server'


def go(*arguments, arch='amd64'):
    environment = dict(os.environ, CGO_ENABLED='0', GOOS='linux', GOARCH=arch)
    return subprocess.check_output(['go', *arguments], cwd=server, env=environment, text=True)


modules = {}
decoder = json.JSONDecoder()
for architecture in ('amd64', 'arm64'):
    remaining = go('list', '-deps', '-json', './cmd/haoxiguan-server', arch=architecture)
    while remaining.strip():
        remaining = remaining.lstrip()
        package, count = decoder.raw_decode(remaining)
        remaining = remaining[count:]
        module = package.get('Module')
        if module and not module.get('Main'):
            if module.get('Replace'):
                raise SystemExit('Review replacement module notices before distributing')
            modules[module['Path']] = module

parts = [
    'Haoxiguan sync server — distribution licenses and notices\n'
    'Generated by tools/generate_server_notices.py from locked Linux runtime dependencies.\n'
    'Each dependency retains its own license. No build timestamp or local paths are included.\n',
    '=== Haoxiguan (MIT) ===\n' + (root / 'LICENSE').read_text().strip(),
    '=== ' + go('env', 'GOVERSION').strip() + ' runtime and standard library ===\n' +
    (Path(go('env', 'GOROOT').strip()) / 'LICENSE').read_text().strip(),
]
for name, module in sorted(modules.items()):
    directory = Path(module['Dir'])
    notices = sorted(path for path in directory.iterdir() if path.is_file() and
                     path.name.upper().startswith(('LICENSE', 'LICENCE', 'COPYING', 'NOTICE', 'COPYRIGHT', 'AUTHORS')))
    if not any(path.name.upper().startswith(('LICENSE', 'LICENCE', 'COPYING')) for path in notices):
        raise SystemExit('Missing upstream license: ' + name)
    parts.append('=== ' + name + ' ' + module['Version'] + ' ===\n' + '\n\n'.join(
        '--- ' + path.name + ' ---\n' + path.read_text().strip() for path in notices))

document = '\n\n'.join(parts) + '\n'
destination = server / 'THIRD_PARTY_NOTICES.txt'
if args.check:
    if not destination.exists() or destination.read_text() != document:
        raise SystemExit('Server notices are stale; run tools/generate_server_notices.py with pinned Go')
else:
    destination.write_text(document)
print(f'{len(modules)} runtime modules: notices ' + ('verified' if args.check else 'written'))
